- en: Summary
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 摘要
- en: 原文：[https://docs.oracle.com/javase/tutorial/essential/exceptions/summary.html](https://docs.oracle.com/javase/tutorial/essential/exceptions/summary.html)
  id: totrans-1
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 原文：[https://docs.oracle.com/javase/tutorial/essential/exceptions/summary.html](https://docs.oracle.com/javase/tutorial/essential/exceptions/summary.html)
- en: "A program can use exceptions to indicate that an error occurred. To throw an\
    \ exception, use the `throw` statement and provide it with an exception object\
    \ \x97 a descendant of `Throwable` \x97 to provide information about the specific\
    \ error that occurred. A method that throws an uncaught, checked exception must\
    \ include a `throws` clause in its declaration."
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: "程序可以使用异常来指示发生了错误。要抛出异常，请使用`throw`语句，并提供一个异常对象 \x97 一个`Throwable`的后代 \x97 以提供有关发生的具体错误的信息。抛出未捕获的已检查异常的方法必须在其声明中包含一个`throws`子句。"
- en: A program can catch exceptions by using a combination of the `try`, `catch`,
    and `finally` blocks.
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: 程序可以通过使用`try`、`catch`和`finally`块的组合来捕获异常。
- en: The `try` block identifies a block of code in which an exception can occur.
  id: totrans-4
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: '`try`块标识出可能发生异常的代码块。'
- en: The `catch` block identifies a block of code, known as an exception handler,
    that can handle a particular type of exception.
  id: totrans-5
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: '`catch`块标识出一个代码块，称为异常处理程序，可以处理特定类型的异常。'
- en: The `finally` block identifies a block of code that is guaranteed to execute,
    and is the right place to close files, recover resources, and otherwise clean
    up after the code enclosed in the `try` block.
  id: totrans-6
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: '`finally`块标识出保证执行的代码块，并且是关闭文件、恢复资源以及在`try`块中封闭的代码之后进行清理的正确位置。'
- en: The `try` statement should contain at least one `catch` block or a `finally`
    block and may have multiple `catch` blocks.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: '`try`语句应至少包含一个`catch`块或一个`finally`块，并且可以有多个`catch`块。'
- en: The class of the exception object indicates the type of exception thrown. The
    exception object can contain further information about the error, including an
    error message. With exception chaining, an exception can point to the exception
    that caused it, which can in turn point to the exception that caused *it*, and
    so on.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 异常对象的类表示抛出的异常类型。异常对象可以包含有关错误的进一步信息，包括错误消息。通过异常链接，一个异常可以指向导致它的异常，后者又可以指向导致*它*的异常，依此类推。
